import Head from "next/head";
import { GlobalStyle } from "../GlobalStyle";
import { Header, PageLayout, SideBar } from "../components/index";

export default function Home() {
	return (
		<>
			<Head>
				<title>Yuya Minamide</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main>
				<GlobalStyle />
				<Header />
				<PageLayout />
				<SideBar />
			</main>
		</>
	);
}
